hostname: <dollar>H
playerlimit: 100
port: 50000
local: false

guardpass: Guard
modpass: Mod
cmpass: Community Manager

gmpass: Universal
gmpass1: Sunday-Monday
gmpass2: Monday-Tuesday
gmpass3: Tuesday-Wednesday
gmpass4: Wednesday-Thursday
gmpass5: Thursday-Friday
gmpass6: Friday-Saturday
gmpass7: Saturday-Sunday

motd: Welcome to my server!
help_msg: TODO

use_district: false
district_ip: 127.0.0.1
district_port: 11037
district_password: enter_password

use_masterserver: true
masterserver_ip: master.aceattorneyonline.com
masterserver_port: 27016
masterserver_name: My First Server
masterserver_description: This is my flashy new server

timeout: 250
debug: false

rp_mode_enabled: false
announce_areas: true

music_change_floodguard:
  times_per_interval: 3
  interval_length: 20
  mute_length: 10
